---
title: "Evolución del IPC anual en España y Catalunya"
author: "Mireia Pérez Martin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Vamos a ver la evolución del IPC anual desde 1961 hasta 2022 en España
```{r}
library(ESdata)
library(tidyverse)

ipc_hist %>% filter(dato == "anual") %>%
  mutate(valor = valor/100) %>%
  ggplot(aes(periodo, valor)) + 
  geom_line(size=1.3) +
  labs(title = "Evolución de la inflación en España", x="año", y="porcentaje de inflación") +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal()

```

Ahora vamos a seleccionar el sector de la alimentación para ver su evolución en comparación con el IPC general
```{r}
ipc_hist_grupos %>% filter(dato == "anual", grupo %in% c("general", "G01")) %>%
  mutate(valor=valor/100) %>%
  ggplot(aes(periodo, valor, col=grupo)) + 
  geom_line(size=1.2) +
  scale_color_manual(name="índice", labels=c("alimentación", "general"), values = c("#D11141", "#606060")) +
  labs(title = "Evolución de la inflación de la alimentación en España", x="Año", y="Porcentaje de inflación") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.position = c(0.1, 0.15))
```
Para ver el peso de cada sector dentro del IPC con un diagrama.
```{r}
ipc_pond %>% filter(periodo==2022 & region=="ES") %>%
  ggplot(aes(x="", y=valor, fill=grupo)) +
  scale_fill_brewer(palette = "Paired")  +
  geom_bar(stat = "Identity") +
  coord_polar("y", start = 0) +
  theme_void()
```

Por último, vamos a ver la evolución del IPC entre Catalunya y España
```{r}
ipc_ccaa %>% filter(region %in% c("ES", "ES-CT") & dato=="indice" & grupo=="general") %>% 
  ggplot(aes(periodo, valor, col=region)) + 
  geom_line(size=1.2) +
  scale_color_manual(name="indice", labels=c("España", "Catalunya"), values = c("#AC88FF", "#5BB300")) +
  labs(title="IPC de Cataluya y España", x="", y="índice") +
  theme(legend.position = c(0.8, 0.15))
```


